In [1]:
import numpy

In [58]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [3]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(11,)

In [8]:
array2 = numpy.array([[1,2,3,4,], [5,6,7,8,],[9,10,11,12]])

In [9]:
type(array2)

numpy.ndarray

In [10]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
array2.shape

(3, 4)

In [13]:
array3 = numpy.full(6,7)
print(array3)

[7 7 7 7 7 7]


In [14]:
모든 값이 0인 numpy array

SyntaxError: invalid syntax (<ipython-input-14-b0a940dd0eea>, line 1)

In [19]:
array3 = numpy.full(6,0)
print(array3)

array4 = numpy.zeros(6,dtype=int)
print(array4)

array5 = numpy.ones(6,dtype=int)
print(array5)

[0 0 0 0 0 0]
[0 0 0 0 0 0]
[1 1 1 1 1 1]


In [20]:
#랜덤한 값을로 생성

array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

[0.22884167 0.91613072 0.37913809 0.90715755 0.05849539 0.49609401]

[0.41679245 0.11951143 0.59439638 0.8883872  0.3968171  0.72049037]


In [22]:
# 연속된 값들이 담긴 numpy array 생성
array1 = numpy.arange(6)
print(array1)

[0 1 2 3 4 5]


In [23]:
#arange(n,m) 을 하면 n 부터 m-1 까지의 값들이 담긴 numpy array가 리턴
array1 = numpy.arange(2,7)
print(array1)

[2 3 4 5 6]


In [24]:
#arange(n,m,s) 을 하면 n 부터 m-1 까지의 값들 중 간격이 s 값들이 리턴
array1 = numpy.arange(3,17, 2)
print(array1)

[ 3  5  7  9 11 13 15]


## 모듈 별명 지어주기

In [29]:
import numpy as np

array1 = np.full(6,0)
array2 = np.zeros(6)
array3 = np.ones(6)
array4 = np.random.random(6)

## 인덱싱, 슬라이싱

In [31]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [33]:
array1[2]

5

In [34]:
array1[-1]

31

In [35]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [36]:
array2 = np.array([2, 1, 3])

In [37]:
array1[array2]

array([5, 3, 7])

In [38]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [39]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [40]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [41]:
#2번 인덱스 ~ 11번 인덱스 사이에 있는 값들 중 2칸씩 건너띈 값 만 받음
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [42]:
array1[2:11:3]

array([ 5, 13, 23])

## numpy 기본 연산

In [50]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [45]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
for i in range(len(array1)):
    array1[i] = 2 * array1[i]

In [49]:
array1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [52]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [53]:
array1  + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [55]:
array1 / array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

## numpy 불린 연산

In [ ]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [56]:
array1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [59]:
array1 % 2 ==0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [60]:
boolean = np.array([ True, True, False, False, False, False, False, False, False,
       False, True])

In [63]:
np.where(boolean)

(array([ 0,  1, 10], dtype=int64),)

In [64]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [65]:
np.where(array1 > 4)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [66]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [67]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [68]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max())
print(array1.min())

31
5


In [70]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.mean())
print(np.median(array1))

15.25
13.5


In [71]:
print(array1.std())
print(array1.var())

8.496322733983215
72.1875
